# Generated by Django 4.2.7 on 2025-12-10 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='destinatarios',
            field=models.ManyToManyField(related_name='reportes_suscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
