# Generated by Django 4.2.7 on 2025-12-30 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve del incidente', max_length=200)),
                ('descripcion', models.TextField(help_text='Describe qué pasó')),
                ('tipo', models.CharField(choices=[('ACCIDENTE', 'Accidente'), ('CASI_ACCIDENTE', 'Casi Accidente'), ('CONDICION_INSEGURA', 'Condición Insegura'), ('ACTO_INSEGURO', 'Acto Inseguro'), ('DAÑO_EQUIPO', 'Daño a Equipo'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_REVISION', 'En Revisión'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Dónde ocurrió', max_length=200)),
                ('fecha_incidente', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo ocurrió')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, help_text='Cuándo se reportó')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidentes/fotos/')),
                ('acciones_tomadas', models.TextField(blank=True, help_text='Qué se hizo para resolver')),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Quién está a cargo de resolverlo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(help_text='Quién reportó el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
