# Generated by Django 4.2.7 on 2026-02-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='area_incidente',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('LABORATORIO', 'Laboratorio'), ('AULAS', 'Aulas'), ('ADMINISTRATIVO', 'Área Administrativa'), ('CAFETERIA', 'Cafetería'), ('PARQUEADERO', 'Parqueadero'), ('MINA_DIDACTICA', 'Mina Didáctica'), ('ZONA_VERDE', 'Zona Verde'), ('CANCHA', 'Cancha Deportiva'), ('PASILLO', 'Pasillo / Corredor'), ('OTRO', 'Otro')], default='OTRO', help_text='Área donde ocurrió el incidente', max_length=50),
        ),
        migrations.AddField(
            model_name='incidente',
            name='documento_afectado',
            field=models.CharField(blank=True, help_text='Documento de la persona afectada', max_length=20),
        ),
        migrations.AddField(
            model_name='incidente',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud de la ubicación del incidente', null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud de la ubicación del incidente', null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='lugar_exacto',
            field=models.CharField(blank=True, help_text='Lugar preciso dentro del centro', max_length=300),
        ),
        migrations.AddField(
            model_name='incidente',
            name='persona_afectada',
            field=models.CharField(blank=True, help_text='Nombre de la persona afectada', max_length=200),
        ),
        migrations.AddField(
            model_name='incidente',
            name='riesgos_identificados',
            field=models.TextField(blank=True, help_text='Riesgos potenciales identificados en el área del incidente'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='rol_afectado',
            field=models.CharField(blank=True, help_text='Rol de la persona afectada', max_length=50),
        ),
        migrations.AddField(
            model_name='incidente',
            name='testigos',
            field=models.TextField(blank=True, help_text='Nombres y datos de contacto de los testigos'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='version_accidente',
            field=models.TextField(blank=True, help_text='Relato detallado del accidente según testigos o involucrados'),
        ),
    ]
