# Generated by Django 4.2.7 on 2026-02-11 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0004_incidente_area_incidente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='usuario_afectado',
            field=models.ForeignKey(blank=True, help_text='Si la persona afectada es usuario del sistema, seleccionarlo aquí', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_como_afectado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='persona_afectada',
            field=models.CharField(blank=True, help_text='Nombre de la persona afectada (si no es usuario del sistema)', max_length=200),
        ),
    ]
