# Generated by Django 4.2.7 on 2026-02-11 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0004_incidente_area_incidente_and_more'),
    ]

    operations = [
        # usuario_afectado ya fue agregado por 0004_incidente_area_incidente_and_more
        migrations.AlterField(
            model_name='incidente',
            name='persona_afectada',
            field=models.CharField(blank=True, help_text='Nombre de la persona afectada (si no es usuario del sistema)', max_length=200),
        ),
    ]
