# Generated by Django 4.2.7 on 2026-02-24 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0005_incidente_usuario_afectado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='persona_afectada',
            field=models.CharField(blank=True, help_text='Nombre de la persona afectada', max_length=200),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='usuario_afectado',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que fue afectado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_como_afectado', to=settings.AUTH_USER_MODEL),
        ),
    ]
