# Generated by Django 4.2.7 on 2026-04-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0006_alter_incidente_persona_afectada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, help_text='Última vez que fue modificado', null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuario que modificó el incidente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialModificacionIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(help_text='Campo que fue modificado', max_length=100)),
                ('valor_anterior', models.TextField(blank=True, help_text='Valor antes del cambio')),
                ('valor_nuevo', models.TextField(blank=True, help_text='Valor después del cambio')),
                ('observacion', models.TextField(blank=True, help_text='Nota del modificador')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='reportes.incidente')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de modificación',
                'verbose_name_plural': 'Historial de modificaciones',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
