# Generated by Django 4.2.7 on 2026-04-09 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0007_incidente_historial_modificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='es_falsa_alarma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fecha_falsa_alarma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='marcado_falso_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_falsos_marcados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='motivo_falsa_alarma',
            field=models.TextField(blank=True),
        ),
    ]
