# Generated by Django 4.2.7 on 2026-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_add_falsa_alarma_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='tipo_documento_afectado',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', help_text='Tipo de documento de la persona afectada', max_length=3),
        ),
    ]
