# Generated by Django 4.2.7 on 2026-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_add_tipo_documento_afectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='personas_afectadas',
            field=models.TextField(blank=True, help_text='Lista de personas afectadas en formato JSON'),
        ),
    ]
