# Generated by Django 4.2.7 on 2025-12-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdificioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('AULAS', 'Bloque de aulas'), ('TALLER', 'Taller'), ('LABORATORIO', 'Laboratorio'), ('ADMINISTRATIVO', 'Oficinas administrativas'), ('Cafeteria', 'Cafeteria'), ('PARQUEADERO', 'Parqueadero'), ('OTRO', 'Otro')], max_length=50)),
                ('piso_minimo', models.IntegerField(default=1)),
                ('piso_maximo', models.IntegerField(default=1)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Edificio/Bloque',
                'verbose_name_plural': 'Edificios/Bloques',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('capacidad', models.IntegerField()),
                ('tipo_terreno', models.CharField(choices=[('ABIERTO', 'Espacio abierto'), ('TECHADO', 'Espacio techado'), ('PARQUE', 'Parque/Zona verde')], default='ABIERTO', max_length=50)),
                ('prioridad', models.IntegerField(default=1, help_text='1=Principal, 2=Secundario, 3=Terciario')),
                ('tiene_agua', models.BooleanField(default=False)),
                ('tiene_sombra', models.BooleanField(default=False)),
                ('tiene_baños', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='puntos_encuentro/')),
            ],
            options={
                'verbose_name': 'Punto de encuentro',
                'verbose_name_plural': 'Puntos de encuentro',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutaEvacuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('inicio_latitud', models.FloatField()),
                ('inicio_longitud', models.FloatField()),
                ('distancia_metros', models.FloatField(help_text='Distancia en metros')),
                ('tiempo_estimado_minutos', models.FloatField(help_text='Tiempo estimado en minutos')),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('bloques_atraviesa', models.ManyToManyField(blank=True, related_name='rutas_evacuacion', to='mapas.edificiobloque')),
                ('punto_fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='mapas.puntoencuentro')),
            ],
            options={
                'verbose_name': 'Ruta de evacuación',
                'verbose_name_plural': 'Rutas de evacuación',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EquipamientoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('EXTINTOR', 'Extintor'), ('BOTIQUIN', 'Botiquin'), ('ALARMA', 'Alarma de emergencia'), ('HIDRANTE', 'Hidrante'), ('SALIDA_EMERGENCIA', 'Señal de salida de emergencia'), ('CAMILLA', 'Camilla'), ('DEA', 'Desfibrilador (DEA)'), ('OTRO', 'Otro')], max_length=30)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('piso', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='OPERATIVO', max_length=20)),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_revision', models.DateTimeField(blank=True, null=True)),
                ('proxima_revision', models.DateTimeField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipamientos/')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='mapas.edificiobloque')),
            ],
            options={
                'verbose_name': 'Equipamiento de seguridad',
                'verbose_name_plural': 'Equipamientos de seguridad',
                'ordering': ['tipo', 'codigo'],
            },
        ),
    ]
