# Generated by Django 4.2.7 on 2025-12-18 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificiobloque',
            name='latitud',
            field=models.FloatField(help_text='Latitud debe estar entre -90 y 90 grados', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='edificiobloque',
            name='longitud',
            field=models.FloatField(help_text='Longitud debe estar entre -180 y 180 grados', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='equipamientoseguridad',
            name='latitud',
            field=models.FloatField(help_text='Latitud debe estar entre -90 y 90 grados', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='equipamientoseguridad',
            name='longitud',
            field=models.FloatField(help_text='Longitud debe estar entre -180 y 180 grados', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='puntoencuentro',
            name='latitud',
            field=models.FloatField(help_text='Latitud debe estar entre -90 y 90 grados', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='puntoencuentro',
            name='longitud',
            field=models.FloatField(help_text='Longitud debe estar entre -180 y 180 grados', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
