# Generated by Django 4.2.7 on 2026-02-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapas', '0003_alter_edificiobloque_latitud_and_more'),
    ]

    # Rama alternativa nunca aplicada en producción.
    # Sus cambios están cubiertos por 0004_rutaevacuacion_waypoints + 0005_edificiobloque_svg.
    # Se deja vacía para preservar el grafo del merge en 0006.
    operations = []
