# Generated by Django 4.2.7 on 2026-02-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapas', '0003_alter_edificiobloque_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificiobloque',
            name='svg_alto',
            field=models.FloatField(default=25, help_text='Alto del edificio en SVG'),
        ),
        migrations.AddField(
            model_name='edificiobloque',
            name='svg_ancho',
            field=models.FloatField(default=40, help_text='Ancho del edificio en SVG'),
        ),
        migrations.AddField(
            model_name='edificiobloque',
            name='svg_x',
            field=models.FloatField(blank=True, help_text='Coordenada X en SVG (calculada desde GPS)', null=True),
        ),
        migrations.AddField(
            model_name='edificiobloque',
            name='svg_y',
            field=models.FloatField(blank=True, help_text='Coordenada Y en SVG (calculada desde GPS)', null=True),
        ),
        migrations.AddField(
            model_name='rutaevacuacion',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, help_text='Lista de coordenadas intermedias: [[lat1,lng1],[lat2,lng2],...]'),
        ),
        migrations.AlterField(
            model_name='edificiobloque',
            name='tipo',
            field=models.CharField(choices=[('AULAS', 'Bloque de aulas'), ('TALLER', 'Taller'), ('LABORATORIO', 'Laboratorio'), ('ADMINISTRATIVO', 'Oficinas administrativas'), ('CAFETERIA', 'Cafeteria'), ('PARQUEADERO', 'Parqueadero'), ('CANCHA', 'Cancha deportiva'), ('ZONA_VERDE', 'Zona verde'), ('MINA', 'Mina didactica'), ('BIBLIOTECA', 'Biblioteca'), ('BODEGA', 'Almacen/Bodega'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='HistorialEstadoEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='mapas.edificiobloque')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EstadoEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NORMAL', 'Normal'), ('DANADO', 'Danado'), ('EVACUANDO', 'Evacuando'), ('CERRADO', 'Cerrado'), ('EN_EMERGENCIA', 'En emergencia')], default='NORMAL', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='mapas.edificiobloque')),
            ],
            options={
                'verbose_name': 'Estado de edificio',
                'verbose_name_plural': 'Estados de edificios',
            },
        ),
    ]
