# Generated by Django 4.2.7 on 2026-02-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0003_alter_edificiobloque_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaevacuacion',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, help_text='Lista de coordenadas intermedias: [[lat1,lng1],[lat2,lng2],...]'),
        ),
        migrations.AlterField(
            model_name='edificiobloque',
            name='tipo',
            field=models.CharField(choices=[('AULAS', 'Bloque de aulas'), ('TALLER', 'Taller'), ('LABORATORIO', 'Laboratorio'), ('ADMINISTRATIVO', 'Oficinas administrativas'), ('CAFETERIA', 'Cafeteria'), ('PARQUEADERO', 'Parqueadero'), ('CANCHA', 'Cancha deportiva'), ('ZONA_VERDE', 'Zona verde'), ('MINA', 'Mina didactica'), ('BIBLIOTECA', 'Biblioteca'), ('BODEGA', 'Almacen/Bodega'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
