# Generated by Django 4.2.7 on 2026-02-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_edificiobloque_svg_alto_edificiobloque_svg_ancho_and_more'),
        ('mapas', '0005_edificiobloque_svg_alto_edificiobloque_svg_ancho_and_more'),
    ]

    operations = [
    ]
