# Generated by Django 4.2.7 on 2026-02-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0006_merge_20260220_0844'),
        ('mapas', '0006_merge_20260227_0804'),
    ]

    operations = [
    ]
