# Generated by Django 4.2.7 on 2026-02-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0007_merge_20260227_0810'),
        ('mapas', '0007_merge_20260227_1341'),
    ]

    operations = [
    ]
