# Generated by Django 4.2.7 on 2026-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0008_merge_20260227_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamientoseguridad',
            name='tipo',
            field=models.CharField(choices=[('EXTINTOR', 'Extintor'), ('BOTIQUIN', 'Botiquin'), ('ALARMA', 'Alarma de emergencia'), ('SALIDA_EMERGENCIA', 'Señal de salida de emergencia'), ('CAMILLA', 'Camilla'), ('OTRO', 'Otro')], max_length=30),
        ),
    ]
