# Generated by Django 4.2.7 on 2026-03-26 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0009_alter_equipamientoseguridad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificiobloque',
            name='poligono',
            field=models.JSONField(blank=True, default=list, help_text='Esquinas del edificio: [[lat1,lng1],[lat2,lng2],...] — se dibuja como polígono en el mapa'),
        ),
        migrations.CreateModel(
            name='NodoCamino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text="Nombre descriptivo (ej: 'Entrada Bloque A')", max_length=100)),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('tipo', models.CharField(choices=[('INTERSECCION', 'Intersección de caminos'), ('ENTRADA', 'Entrada de edificio'), ('PUNTO_ENCUENTRO', 'Punto de encuentro'), ('SALIDA_CAMPUS', 'Salida del campus'), ('OTRO', 'Otro')], default='INTERSECCION', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_camino', to='mapas.edificiobloque')),
                ('punto_encuentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_camino', to='mapas.puntoencuentro')),
            ],
            options={
                'verbose_name': 'Nodo de camino',
                'verbose_name_plural': 'Nodos de camino',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TramoCamino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIA_INTERNA', 'Vía interna'), ('VIA_PRINCIPAL', 'Vía principal'), ('PASILLO', 'Pasillo interior'), ('RAMPA', 'Rampa accesible'), ('ESCALERA', 'Escalera')], default='VIA_INTERNA', max_length=20)),
                ('distancia_metros', models.FloatField(help_text='Distancia en metros — se calcula automáticamente al guardar si se deja en 0')),
                ('bidireccional', models.BooleanField(default=True, help_text='Si False, solo se puede transitar origen → destino')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_entrada', to='mapas.nodocamino')),
                ('nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_salida', to='mapas.nodocamino')),
            ],
            options={
                'verbose_name': 'Tramo de camino',
                'verbose_name_plural': 'Tramos de camino',
                'indexes': [models.Index(fields=['activo'], name='mapas_tramo_activo_8f8d54_idx')],
                'unique_together': {('nodo_origen', 'nodo_destino')},
            },
        ),
        migrations.AddIndex(
            model_name='nodocamino',
            index=models.Index(fields=['activo'], name='mapas_nodoc_activo_1afb55_idx'),
        ),
    ]
