# Generated by Django 4.2.7 on 2026-02-04 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('INCIDENTE', 'Incidente'), ('SISTEMA', 'Sistema'), ('ASISTENCIA', 'Asistencia'), ('CAPACITACION', 'Capacitacion'), ('RECORDATORIO', 'Recordatorio'), ('INFO', 'Informativo')], default='INFO', max_length=20)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('url_relacionada', models.CharField(blank=True, max_length=500)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['destinatario', '-fecha_creacion'], name='usuarios_no_destina_a6867c_idx'), models.Index(fields=['destinatario', 'leida'], name='usuarios_no_destina_2c52a0_idx')],
            },
        ),
    ]
