# Generated by Django 4.2.7 on 2026-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_add_fichas_asignadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_brigada',
            field=models.BooleanField(default=False, help_text='Indica si este usuario forma parte de la brigada de emergencias', verbose_name='Miembro de Brigada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente de aprobación'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10, verbose_name='Estado de cuenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('COORDINADOR_SST', 'Coordinador SST'), ('APRENDIZ', 'Aprendiz'), ('INSTRUCTOR', 'Instructor'), ('ADMINISTRATIVO', 'Administrativo'), ('VIGILANCIA', 'Vigilancia'), ('BRIGADA', 'Brigada de Emergencia'), ('VISITANTE', 'Visitante')], default='APRENDIZ', max_length=20),
        ),
    ]
