# Generated by Django 4.2.7 on 2026-04-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_seed_programas_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_notif_email',
            field=models.BooleanField(default=True, help_text='Recibir alertas de emergencias e incidentes críticos por correo electrónico', verbose_name='Notificaciones por correo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='recibir_notif_whatsapp',
            field=models.BooleanField(default=False, help_text='Recibir alertas de emergencias por WhatsApp (requiere número de teléfono registrado)', verbose_name='Notificaciones por WhatsApp'),
        ),
    ]
