# Generated by Django 4.2.7 on 2026-04-10 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_add_notif_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número de ficha')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='usuarios.programaformacion', verbose_name='Programa de formación')),
            ],
            options={
                'verbose_name': 'Ficha de Formación',
                'verbose_name_plural': 'Fichas de Formación',
                'ordering': ['numero'],
                'unique_together': {('programa', 'numero')},
            },
        ),
    ]
