# Generated by Django 4.2.7 on 2026-04-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_add_ficha_formacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='recibir_notif_whatsapp',
        ),
        migrations.AddField(
            model_name='usuario',
            name='callmebot_apikey',
            field=models.CharField(blank=True, help_text='Clave para recibir alertas por WhatsApp vía CallMeBot', max_length=20, verbose_name='API Key de CallMeBot'),
        ),
    ]
