# Generated by Django 4.2.7 on 2026-04-12 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_add_callmebot_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='visitante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitante_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='persona_a_visitar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
