# Generated by Django 4.2.7 on 2026-04-12 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_visitante_email_usuario_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
