# Generated by Django 4.2.7 on 2025-12-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('AFORO', 'Reporte de Aforo'), ('ASISTENCIA', 'Reporte de Asistencia'), ('INCIDENTES', 'Reporte de Incidentes'), ('EQUIPAMIENTO', 'Estado de Equipamiento'), ('SEGURIDAD', 'Reporte de Seguridad')], max_length=50)),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=10)),
                ('hora_generacion', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('ultima_generacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('datos_json', models.JSONField(default=dict)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.configuracionreporte')),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
