# Generated by Django 4.2.7 on 2025-12-10 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencias', '0001_initial'),
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionemergencia',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacionemergencia',
            name='emergencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='emergencias.emergencia'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='atendida_por',
            field=models.ManyToManyField(blank=True, related_name='emergencias_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to='mapas.edificiobloque'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='reportada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_reportadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias', to='emergencias.tipoemergencia'),
        ),
        migrations.AddField(
            model_name='brigadaemergencia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brigada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emergencia',
            index=models.Index(fields=['-fecha_hora_reporte'], name='emergencias_fecha_h_c292cb_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencia',
            index=models.Index(fields=['estado'], name='emergencias_estado_704786_idx'),
        ),
    ]
