# Generated by Django 4.2.7 on 2025-12-18 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='estado',
            field=models.CharField(choices=[('REPORTADA', 'Reportada'), ('EN_ATENCION', 'En atención'), ('CONTROLADA', 'Controlada'), ('RESUELTA', 'Resuelta'), ('FALSA_ALARMA', 'Falsa alarma')], db_index=True, default='REPORTADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_hora_reporte',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='latitud',
            field=models.FloatField(help_text='Latitud debe estar entre -90 y 90 grados', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='longitud',
            field=models.FloatField(help_text='Longitud debe estar entre -180 y 180 grados', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
