# Generated by Django 4.2.7 on 2026-02-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0003_alter_emergencia_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacionemergencia',
            old_name='emergencias',
            new_name='emergencia',
        ),
    ]
