# Generated by Django 4.2.7 on 2026-02-09 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencias', '0004_rename_emergencias_to_emergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='fecha_hora_falsa_alarma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='marcada_falsa_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='falsas_alarmas_marcadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='motivo_falsa_alarma',
            field=models.TextField(blank=True),
        ),
    ]
