# Generated by Django 4.2.7 on 2026-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0005_emergencia_fecha_hora_falsa_alarma_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emergencia',
            index=models.Index(fields=['estado', 'fecha_hora_reporte'], name='idx_emergencia_estado_fecha'),
        ),
    ]
