# Generated by Django 4.2.7 on 2026-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0006_emergencia_idx_emergencia_estado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoemergencia',
            name='alerta_masiva',
            field=models.BooleanField(default=False, help_text='Si está activo, al reportarse se notifica a TODOS los usuarios del sistema, no solo a la brigada.', verbose_name='Alerta masiva'),
        ),
        migrations.AddField(
            model_name='tipoemergencia',
            name='solo_autorizado',
            field=models.BooleanField(default=False, help_text='Si está activo, solo Coordinador, Brigada y Administrativo pueden reportar este tipo de emergencia.', verbose_name='Solo personal autorizado'),
        ),
    ]
