# Generated by Django 4.2.7 on 2026-04-08 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencias', '0010_fix_tipos_solo_naturales'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvacuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, help_text='Instructor u otro usuario que confirmo la presencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuaciones_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_evacuacion', to='emergencias.emergencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Evacuación',
                'verbose_name_plural': 'Registros de Evacuación',
                'ordering': ['-fecha_confirmacion'],
                'unique_together': {('emergencia', 'usuario')},
            },
        ),
    ]
