# Generated by Django 4.2.7 on 2026-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0011_add_registro_evacuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroevacuacion',
            name='ausente',
            field=models.BooleanField(default=False, help_text='Marcado como no presente en el punto de encuentro'),
        ),
    ]
