# Generated by Django 4.2.7 on 2026-04-10 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0012_add_ausente_to_registro_evacuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud debe estar entre -90 y 90 grados', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud debe estar entre -180 y 180 grados', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
