# Generated by Django 4.2.7 on 2025-12-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aforo_maximo', models.IntegerField(default=2000)),
                ('aforo_minimo', models.IntegerField(default=1800)),
                ('mensaje_alerta', models.TextField(default='Se está alcanzando el aforo máximo del centro')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de aforo',
                'verbose_name_plural': 'Configuraciones de aforo',
            },
        ),
        migrations.CreateModel(
            name='Geocerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Centro Minero SENA', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('centro_latitud', models.FloatField(default=5.5339)),
                ('centro_longitud', models.FloatField(default=-73.3674)),
                ('radio_metros', models.IntegerField(default=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Geocerca',
                'verbose_name_plural': 'Geocercas',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('latitud_ingreso', models.FloatField(blank=True, null=True)),
                ('longitud_ingreso', models.FloatField(blank=True, null=True)),
                ('metodo_ingreso', models.CharField(choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual'), ('QR', 'Código QR')], default='AUTOMATICO', max_length=15)),
                ('fecha_hora_egreso', models.DateTimeField(blank=True, null=True)),
                ('latitud_egreso', models.FloatField(blank=True, null=True)),
                ('longitud_egreso', models.FloatField(blank=True, null=True)),
                ('metodo_egreso', models.CharField(blank=True, choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual'), ('QR', 'Código QR')], max_length=15, null=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-fecha_hora_ingreso'],
            },
        ),
    ]
