# Generated by Django 4.2.7 on 2025-12-18 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocerca',
            name='centro_latitud',
            field=models.FloatField(default=5.5339, help_text='Latitud debe estar entre -90 y 90 grados', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='geocerca',
            name='centro_longitud',
            field=models.FloatField(default=-73.3674, help_text='Longitud debe estar entre -180 y 180 grados', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='geocerca',
            name='radio_metros',
            field=models.IntegerField(default=200, help_text='Radio en metros (mínimo 1 metro)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
