# Generated by Django 4.2.7 on 2026-02-16 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0003_alter_geocerca_centro_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocerca',
            name='centro_latitud',
            field=models.FloatField(default=5.7303596, help_text='Latitud debe estar entre -90 y 90 grados', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='geocerca',
            name='centro_longitud',
            field=models.FloatField(default=-72.8943613, help_text='Longitud debe estar entre -180 y 180 grados', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_egreso',
            field=models.CharField(blank=True, choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_ingreso',
            field=models.CharField(choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual')], default='AUTOMATICO', max_length=15),
        ),
    ]
