# Generated by Django 4.2.7 on 2026-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0004_alter_geocerca_centro_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_egreso',
            field=models.CharField(blank=True, choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_ingreso',
            field=models.CharField(choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual')], default='AUTOMATICO', max_length=15),
        ),
    ]
