# Generated by Django 4.2.7 on 2026-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0007_update_geocerca_radio_200'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['usuario', 'fecha_hora_ingreso'], name='idx_acceso_usuario_fecha'),
        ),
    ]
