# Generated by Django 4.2.7 on 2026-04-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acceso', '0008_registroacceso_idx_acceso_usuario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_egreso',
            field=models.CharField(blank=True, choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual'), ('QR', 'Código QR')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='metodo_ingreso',
            field=models.CharField(choices=[('AUTOMATICO', 'Deteccion automática'), ('MANUAL', 'Detección manual'), ('QR', 'Código QR')], default='AUTOMATICO', max_length=15),
        ),
    ]
